### ISSUE TITLE
Ambiguity regarding left or right event

### ISSUE THREAD

**Issue by kwdoyle** [kwdoyle/CMD-Detection#2]
In most of the files from the other site, triggers processed for a given block have some events with, for example, ID 80 and other events with ID 30. It is unknown whether these blocks should be left or right hand blocks.

This breaks the cleaning functions, as there's no way to tell that these events should be kept. The cleaning functions check each event to see if the subsequent event is the next ID in a given matching pair (80 with 70, 50 with 60, 30 with 40, and 10 with 20). All the events who have a subsequent event that is not part of their matching pair will be removed. This works to detect bad events when the left/right pairs are at least processed correctly. In this case, however, blocks that apparently should be kept are removed.

Before cleaning:
![Screen Shot 2020-12-10 at 11 02 38 AM](https://user-images.githubusercontent.com/6235145/101797091-a07f2980-3ad7-11eb-8d30-8ed91f3af3f7.png)

After cleaning:
![Screen Shot 2020-12-10 at 11 15 10 AM](https://user-images.githubusercontent.com/6235145/101798355-fdc7aa80-3ad8-11eb-8f0a-e10fb7762bfc.png)

**Comment by fraimondo** [comment]
Did they plug the DC channels in the same order?

There’s no way that 30 and 80 get mixed within one block. Same for 40 and 70.

**Comment by kwdoyle** [comment]
Then that's probably the issue.. They most likely plugged in the cables incorrectly. I assume there's no fix to this though?

**Comment by fraimondo** [comment]
There's always a fix. Let's figure out how they plugged the cables.

This is 80 `# 128 = 1000 0000b` and this is 40 `# 144 = 1001 0000b` So it seems that bit 0x10 is changing between events of the same block. That would be DC6. And the only ones that should change between events in the same block are DC5 and DC7.

Maybe they did use different trigger channels. Did you try looking at the raw to see how it looks? Do they have the "stairs" somehow? If you point me to which file is it, I can quickly take a look.

**Comment by kwdoyle** [comment]
This is recording17 from the "deidentified fife 2" folder. If I had to guess, they probably just plugged them in the wrong order.

**Comment by fraimondo** [comment]
The stairs are fine:
![Screenshot 2020-12-10 at 17 56 02](https://user-images.githubusercontent.com/4493699/101803580-f9b77f00-3b10-11eb-9fb1-335d917cab53.png)

The issue here is that this is a Local Global recording. I did that paradigm so much that I recognise the trigger pattern.

Here you can see the habituation period ending (HSTD), then 5 LSGS trials and then 1 LDGD trial.
![Screenshot 2020-12-10 at 17 57 57](https://user-images.githubusercontent.com/4493699/101803834-3e431a80-3b11-11eb-8442-8047302e7225.png)

**Comment by kwdoyle** [comment]
Interesting. So that's good news then. Is it possible that last event block is part of the actual auditory paradigm? All of their recordings look like this:
![example file](https://user-images.githubusercontent.com/6235145/101807451-20f75780-3ae3-11eb-821b-649701650e01.png)


implying  events from the correct paradigm are present, but the EEG was clipped too early. Is there any way local-global triggers could be processed like the auditory ones?

**Comment by fraimondo** [comment]
Yes. In the one that you sent me first, I found the stairs again later, and the MCP stars there.
![Screenshot 2020-12-10 at 18 37 38](https://user-images.githubusercontent.com/4493699/101808579-ced02980-3b16-11eb-86c7-d671178d5acc.png)

**Comment by kwdoyle** [comment]
Ok, good to know; thank you for checking. I'll reach out to them and confirm that they should re-clip/export their files.
